name: CD for Uniphar.Dotnet.Cli project

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  Package_CD:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Uniphar.Dotnet.Cli

    steps:

      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_PLATFORM_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
